from ..models import db
from app.models import Event
from datetime import time



def seeded_events():
    seeder_events = [
        Event(
            owner_id=1,
            name="Tiesto, Brooklyn Mirage",
            description="TIËSTO MAKES HIS DEBUT AT THE BROOKLYN MIRAGE THIS DECEMBER.",
            address="123 Main Street",
            state="New York",
            city="New York",
            zipcode="90001",
            event_starts="2022-12-05",
            event_ends="2022-12-06",
            ticket_quantity=300,
            start_time=time(18, 00),
            end_time=time(23, 00),
            preview_image="https://brooklyneagle.com/wp-content/uploads/2019/06/PARADISE_NYC_0924_003802-2792_ALIVECOVERAGE.jpg",
    ),
        Event(
            owner_id=2,
            name="Diplo, Brooklyn Mirage",
            description="DIPLO MAKES HIS DEBUT AT THE BROOKLYN MIRAGE THIS DECEMBER.",
            address="123 Main Street",
            state="NY",
            city="Brooklyn",
            zipcode="21231",
            event_starts="2022-12-17",
            event_ends="2022-12-18",
            ticket_quantity=300,
            start_time=time(18, 00),
            end_time=time(23, 00),
            preview_image="https://edm.com/.image/t_share/MTc2OTU0ODU5MTM0NzIzNDQw/calder-wilson-for-insomniac-events-5-e1573670725699.jpg",
    ),
        Event(
            owner_id=3,
            name="Martin Garrix at Ezoo",
            description="Martin Garrix at Electric Zoo",
            address="123 Main Street",
            state="NY",
            city="New York",
            zipcode="90001",
            event_starts="2022-12-18",
            event_ends="2022-12-19",
            ticket_quantity=300,
            start_time=time(18, 00),
            end_time=time(23, 00),
            preview_image="https://weraveyou.com/wp-content/uploads/2022/07/Tomorrowland-2022-01.jpg",
        ),
        Event(
            owner_id=1,
            name="Kygo at Madison Square Garden",
            description="Kygo at Madison Square Garden, New York City With special guest: Gryffin and more",
            address="123 Main Street",
            state="NY",
            city="Manhattan",
            zipcode="90001",
            event_starts="2022-12-20",
            event_ends="2022-12-21",
            ticket_quantity=300,
            start_time=time(18, 00),
            end_time=time(23, 00),
            preview_image="https://edm.com/.image/t_share/MTkwMzg2ODg5NjU4NzM4MDY4/281679937_571680417650489_6108048098757542031_n.jpg",
        ),
        Event(
            owner_id=2,
            name="Zedd at Marquee",
            description="Zedd at Marquee, New York City With special guest: Dillion Francis, Snakehips, and more",
            address="123 Main Street",
            state="NY",
            city="Manhattan",
            zipcode="90001",
            event_starts="2022-12-20",
            event_ends="2022-12-21",
            ticket_quantity=300,
            start_time=time(18, 00),
            end_time=time(23, 00),
            preview_image="https://magprod-1a27b.kxcdn.com/wp-content/uploads/2022/03/New-York_Marquee_Pic-3.jpg",
        ),
        Event(
            owner_id=3,
            name="Odeza at Madison Square Garden",
            description="Odeza at Madison Square Garden, New York City With special guest: Louis The Child, Jai Wolf, and more",
            address="123 Main Street",
            state="NY",
            city="Manhattan",
            zipcode="90001",
            event_starts="2022-12-20",
            event_ends="2022-12-21",
            ticket_quantity=300,
            start_time=time(18, 00),
            end_time=time(23, 00),
            preview_image="https://www.thenocturnaltimes.com/wp-content/uploads/2018/05/32640612_1865188010179633_2516770867459915776_n-1.jpg",
        ),
        Event(
            owner_id=1,
            name="Illenium at Madison Square Garden",
            description="Illenium at Madison Square Garden, New York City With special guest: TroyBoi, Said The Sky, and more",
            address="123 Main Street",
            state="NY",
            city="Manhattan",
            zipcode="90001",
            event_starts="2022-12-20",
            event_ends="2022-12-21",
            ticket_quantity=300,
            start_time=time(18, 00),
            end_time=time(23, 00),
            preview_image="https://dancingastronaut.com/wp-content/uploads/2019/11/Illenium-MSG-8.jpg",
        ),
        Event(
            owner_id=2,
            name="Yellow Claw at Marquee",
            description="Yellow Claw at Marquee, New York City With special guest: DVBBS and more",
            address="123 Main Street",
            state="NY",
            city="Manhattan",
            zipcode="90001",
            event_starts="2022-12-20",
            event_ends="2022-12-21",
            ticket_quantity=300,
            start_time=time(18, 00),
            end_time=time(23, 00),
            preview_image="https://www.ismaya.com/storage/app/uploads/public/5e2/177/c5b/5e2177c5b8c8a428561302.jpg",
        ),
        Event(
            owner_id=3,
            name="KSHMR at Marquee",
            description="KSHMR at Marquee, New York City With special guest: Axwell /\ Ingrosso, and more",
            address="123 Main Street",
            state="NY",
            city="Manhattan",
            zipcode="90001",
            event_starts="2022-12-23",
            event_ends="2022-12-24",
            ticket_quantity=300,
            start_time=time(18, 00),
            end_time=time(23, 00),
            preview_image="https://taogroup.com/wp-content/uploads/2019/09/03_16_18.Borgeous.Marquee-26.jpg",
        ),
    ]
    for event in seeder_events:
        db.session.add(event)
        db.session.commit()

def undo_events():
    db.session.execute('TRUNCATE events RESTART IDENTITY CASCADE;')
    db.session.commit()
